'''
PDFOptions.py
Created on 2026-08-24 by Kale Stahl
Last Updated on 2026-08-24 by Kale Stahl
'''

from reportlab.lib.units import mm, inch
from paperSize import PaperSizes

class PDFOptions:
    '''
    Class to store the PDF options for the GUI.
    '''  

    def __init__(self,
                    output_file = "autogeneratedproxies.pdf",
                    cards_per_page = 9,
                    paper = PaperSizes.Letter.value,
                    horizontal_margin = 0.25 * inch,
                    vertical_margin = 0.25 * inch,
                    horizontal_spacing = 0.25 * inch,
                    vertical_spacing = 0.25 * inch,
                    card_width = 2.5 * inch,
                    card_height = 3.5 * inch,
                    orientation = 'portrait',
                    saturation = 1.0,
                    brightness = 1.0,
                    contrast = 1.0,
                    red = 1.0,
                    green = 1.0,    
                    blue = 1.0,
                    cardBacks = False,
                    cardBackText = "",
                    proxyText = "",
                ):
            '''
            Initialize the PDFOptions object with its options.
            
            Parameters
            ----------
            output_file : str, optional
                The name of the output PDF file. The default is "autogeneratedproxies.pdf".
            cards_per_page : int, optional
                The number of cards to be printed per page. The default is 9.
            paper : PaperSizes, optional
                The paper size to be used for the PDF. The default is PaperSizes.Letter.value.
            horizontal_margin : float, optional
                The horizontal margin for the PDF in inches. The default is 0.25 * inch.
            vertical_margin : float, optional
                The vertical margin for the PDF in inches. The default is 0.25 * inch.
            horizontal_spacing : float, optional
                The horizontal spacing between cards in the PDF in inches. The default is 0.25 * inch.
            vertical_spacing : float, optional
                The vertical spacing between cards in the PDF in inches. The default is 0.25 * inch.
            card_width : float, optional
                The width of each card in the PDF in inches. The default is 2.5 * inch.
            card_height : float, optional
                The height of each card in the PDF in inches. The default is 3.5 * inch.
            orientation : str, optional
                The orientation of the PDF. The default is 'portrait'.
            saturation : float, optional
                The saturation of the PDF. The default is 1.0.
            brightness : float, optional
                The brightness of the PDF. The default is 1.0.
            contrast : float, optional
                The contrast of the PDF. The default is 1.0.
            red : float, optional
                The red component of the PDF color. The default is 1.0.
            green : float, optional
                The green component of the PDF color. The default is 1.0.
            blue : float, optional
                The blue component of the PDF color. The default is 1.0.
            cardBacks : bool, optional
                Whether to print backs for the cards. The default is False.
            cardBackText : str, optional
                The text to be printed on the backs of the cards. The default is "".
            proxyText : str, optional
                The text to be printed on the proxies. The default is "".
            '''
            self._output = output_file
            self._cardsPerPage = cards_per_page
            self._pageWidth, self._pageHeight = paper.width, paper.height
            self._cardWidth, self._cardHeight = card_width, card_height
            self._orientation = orientation
            self._saturation = saturation
            self._brightness = brightness
            self._contrast = contrast
            self._red = red
            self._green = green
            self._blue = blue
            self._cardBacks = cardBacks
            self._cardBackText = cardBackText
            self._proxyText = proxyText
            self._horizontal_margin = horizontal_margin
            self._vertical_margin = vertical_margin
            self._horizontal_spacing = horizontal_spacing
            self._vertical_spacing = vertical_spacing
