'''
ProxiesFromDeck.py
Kale Stahl
Last Updated: 5/17/2026
'''

import os
import re
import unicodedata
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
import requests
from io import BytesIO
from PIL import Image, ImageEnhance, ImageFilter
from pokemontcgsdk import Card, RestClient
from reportlab.pdfgen import canvas
from reportlab.lib.units import mm, inch
from reportlab.lib.utils import ImageReader
from reportlab.lib import colors
import colorsys
import numpy as np

### Set your API key (get one for free at https://pokemontcg.io/)
from dotenv import load_dotenv
load_dotenv()
api_key = os.getenv("API_KEY")
RestClient.configure(api_key)

### Constants
CARD_W = 63 * mm
CARD_H = 88 * mm
COLS = 3
ROWS = 3
OUTPUT_FILE = "AutoGeneratedProxies.pdf"
DECKLIST_FILE = "decklist.txt"
GRID_BOOL = False  # Set to True to draw cutting grid lines on the PDF"

image_cache = {}
image_cache_lock = threading.Lock()
image_session = requests.Session()
CARD_QUERY_PAGE_SIZE = 100

### This can be changed if you want better resolution.
TARGET_DPI = 600
CARD_WIDTH_IN = CARD_W / inch
CARD_HEIGHT_IN = CARD_H / inch
TARGET_W = int(CARD_WIDTH_IN * TARGET_DPI)  
TARGET_H = int(CARD_HEIGHT_IN * TARGET_DPI)  

### Print Tweaking - these can be adjusted to your preference, but generally a slight boost in saturation/brightness/contrast helps make the images pop when printed on matte media. Adjust as needed or set to 1.0 for no change.
SATURATION = 1.15   # 1.0 = unchanged
BRIGHTNESS = 1.06  # slight lift for matte media
CONTRAST = 1.08    # optional subtle contrast boost

### Get image from URL with caching and upscale to target print resolution
def get_image(url):
    with image_cache_lock:
        cached = image_cache.get(url)
    if cached is not None:
        return cached

    r = image_session.get(url, timeout=20)
    img = Image.open(BytesIO(r.content)).convert("RGB")

    # Upscale to target print resolution
    img = img.resize((TARGET_W, TARGET_H), Image.LANCZOS)

    img = ImageEnhance.Color(img).enhance(SATURATION)
    img = ImageEnhance.Brightness(img).enhance(BRIGHTNESS)
    img = ImageEnhance.Contrast(img).enhance(CONTRAST)
    img = adjust_gamma(img, 0.92)

    img = img.filter(
        ImageFilter.UnsharpMask(
            radius=0.5,
            percent=120,
            threshold=2
        )
    )

    with image_cache_lock:
        image_cache[url] = img

    return img

### Adjusts gamma
def adjust_gamma(img, gamma=0.92):
    inv = 1.0 / gamma

    table = [
        ((i / 255.0) ** inv) * 255
        for i in range(256)
    ]

    return img.point(table * 3)

### Fixes Blue and Green cards for printing (CURRENTLY UNUSED)
def boost_blues_greens(img, sat_boost=1.25):
    arr = np.array(img).astype(np.float32) / 255.0

    for y in range(arr.shape[0]):
        for x in range(arr.shape[1]):
            r, g, b = arr[y, x]

            h, s, v = colorsys.rgb_to_hsv(r, g, b)

            # Boost greens/cyans/blues
            # HSV hue:
            # green ≈ 0.25-0.45
            # cyan  ≈ 0.45-0.58
            # blue  ≈ 0.58-0.75
            if 0.25 <= h <= 0.75:
                s *= sat_boost
                s = min(s, 1.0)

            r, g, b = colorsys.hsv_to_rgb(h, s, v)
            arr[y, x] = [r, g, b]

    arr = (arr * 255).clip(0, 255).astype(np.uint8)
    return Image.fromarray(arr)

### Parse a line of the decklist - expects format like "4 Pikachu BWP 25"
def parse_line(line):
    line = line.strip()

    if not line:
        return None

    m = re.match(r"^(\d+)\s+(.+?)\s+([A-Z0-9]+)\s+([A-Z0-9]+)$", line)

    if not m:
        return None

    count = int(m.group(1))
    name = m.group(2).strip()
    set_code = m.group(3).strip()
    number = m.group(4).strip()

    return count, name, set_code, number

### Normalize card name for API queries - convert stars to symbols and energy letters to {L}, {W}, etc. to maximize chances of matching weird card names in the API
def normalize_name_for_api(name):
    name = re.sub(r"\bprism\s*star\b", "◇", name, flags=re.IGNORECASE)
    name = re.sub(r"\bstar\b", "★", name, flags=re.IGNORECASE)

    def replace_energy(match):
        letters = match.group(1)
        return " ".join(f"{{{c}}}" for c in letters)

    # ONLY convert trailing energy letters for Unit/Blend Energy cards
    if re.search(r"\b(unit|blend)\s+energy\b", name, re.IGNORECASE):
        name = re.sub(r"\b([LWMFPDC]+)\b$", replace_energy, name)

    name = re.sub(r"\s+", " ", name).strip()
    return name

### Normalize text for matching - remove accents, lowercase, and normalize stars to maximize chances of matching weird card names in the API
def norm(text):
    text = text.lower()

    text = text.replace("★", "star")
    text = text.replace("◇", "prism star")

    text = unicodedata.normalize("NFKD", text)
    text = "".join(c for c in text if not unicodedata.combining(c))

    # strip punctuation
    text = re.sub(r"[^a-z0-9\s]", "", text)

    text = re.sub(r"\s+", " ", text).strip()

    return text

### Build a unique set of cards from the decklist, keyed by normalized name + number + set code to minimize API calls
def build_unique(deck_lines):
    unique = {}
    counts = {}

    for line in deck_lines:
        parsed = parse_line(line)
        if not parsed:
            continue

        count, name, set_code, number = parsed
        key = (norm(name), number, set_code.upper())

        if key not in unique:
            unique[key] = {
                "name": name,
                "number": number,
                "set_code": set_code.upper()
            }
            counts[key] = 0

        counts[key] += count

    return unique, counts

### Build possible number variants based on set code and original number, to maximize chances of matching weird promo numbering schemes
### (Limitless/TGCLive uses different numbering sometimes so this hopefully catches those)
def build_possible_numbers(number, set_code):
    number = str(number).upper().strip()
    nums = {number}

    try:
        n_int = int(number)
    except:
        n_int = None

    if set_code == "BWP":
        if n_int is not None:
            nums.update({
                f"BW{n_int}",
                f"BW{n_int:02d}",
                str(n_int)
            })

    elif set_code == "XYP":
        if n_int is not None:
            nums.update({
                f"XY{n_int}",
                f"XY{n_int:02d}",
                str(n_int)
            })

    elif set_code == "SMP":
        if n_int is not None:
            nums.update({
                f"SM{n_int}",
                f"SM{n_int:02d}",
                str(n_int)
            })
    elif set_code == "WP":
        if n_int is not None:
            nums.update({
                f"WP{n_int}",
                f"WP{n_int:02d}",
                str(n_int)
            })

    # General fallback for weird promos
    if n_int is not None:
        nums.add(str(n_int))
        cleaned_set_code = re.sub(r"[^A-Z]", "", set_code.upper())
        if cleaned_set_code:
            nums.update({
                f"{cleaned_set_code}{n_int}",
                f"{cleaned_set_code}{n_int:02d}"
            })


    return nums

### Strip bracketed suffixes from a card name for query fallback handling
### Example: "Ancient Technical Machine [Rock]" -> "Ancient Technical Machine"
def strip_bracket_suffix(name):
    return re.sub(r"\s*\[[^\]]+\]\s*$", "", name).strip()

### Build fallback name variants for cards that may be listed in alternate spellings
### or with special gender/symbol forms that the API requires.
def build_name_variants(api_name):
    variants = [api_name]
    bracket_safe = re.sub(r"[\[\]]", "", api_name).strip()
    if bracket_safe != api_name:
        variants.append(bracket_safe)

    stripped_name = strip_bracket_suffix(api_name)
    if stripped_name and stripped_name not in variants:
        variants.append(stripped_name)

    if re.search(r"\bNidoran\s*(?:F|Female)\b", api_name, flags=re.IGNORECASE):
        variants.append(re.sub(r"\bNidoran\s*(?:F|Female)\b", "Nidoran♀", api_name, flags=re.IGNORECASE))
    if re.search(r"\bNidoran\s*(?:M|Male)\b", api_name, flags=re.IGNORECASE):
        variants.append(re.sub(r"\bNidoran\s*(?:M|Male)\b", "Nidoran♂", api_name, flags=re.IGNORECASE))

    seen = set()
    ordered = []
    for v in variants:
        v = v.strip()
        if v and v not in seen:
            seen.add(v)
            ordered.append(v)

    return ordered

### Build tokenized name queries to allow matching alternate spellings
### like "Mr Mime", "Type Null", or "Farfetchd" when exact phrase search fails.
def build_tokenized_queries(name):
    tokens = re.findall(r"[A-Za-z0-9]+", name)
    if not tokens:
        return []

    queries = [" ".join(f"name:{token}" for token in tokens)]

    # Allow an apostrophe-style fallback for names such as Farfetch'd where the decklist
    # may omit the apostrophe.
    for idx, token in enumerate(tokens):
        if len(token) > 2 and token.lower().endswith("d") and "'" not in token:
            stripped = token[:-1]
            alt_tokens = tokens[:idx] + [stripped, token[-1]] + tokens[idx+1:]
            alt_query = " ".join(f"name:{t}" for t in alt_tokens)
            if alt_query not in queries:
                queries.append(alt_query)

    return queries

### Fetch candidate cards from API for each unique item in the decklist, using multiple query strategies to maximize chances
### of finding a match. There is 10000% a better way to do this, but this is what I first came up with and it seems to not break always.
def fetch_candidates(unique_items, max_workers=12):
    results = {}

    def fetch(item):
        name = item["name"]
        number = item["number"]
        set_code = item["set_code"]

        api_name = normalize_name_for_api(name)
        possible_numbers = sorted(build_possible_numbers(number, set_code), key=lambda v: (len(v), v))

        def quote_value(value):
            return value.replace('\\', '\\\\').replace('"', '\\"')

        quoted_name = quote_value(api_name)
        bracket_safe = re.sub(r"[\[\]]", "", api_name)
        bracket_safe = re.sub(r"\s+", " ", bracket_safe).strip()
        quoted_bracket_safe = quote_value(bracket_safe)

        queries = []

        name_variants = build_name_variants(api_name)

        # Try exact name + number + set first, then broaden only if needed.
        for num in possible_numbers:
            for variant in name_variants:
                quoted_variant = quote_value(variant)
                queries.extend([
                    f'name:"{quoted_variant}" number:{num} set.ptcgoCode:{set_code}',
                    f'name:"{quoted_variant}" number:{num} set.id:{set_code.lower()}',
                    f'name:"{quoted_variant}" number:{num}'
                ])

                for token_query in build_tokenized_queries(variant):
                    queries.extend([
                        f'{token_query} number:{num} set.ptcgoCode:{set_code}',
                        f'{token_query} number:{num} set.id:{set_code.lower()}',
                        f'{token_query} number:{num}'
                    ])

        # Fallbacks without number
        for variant in name_variants:
            quoted_variant = quote_value(variant)
            queries.extend([
                f'name:"{quoted_variant}" set.id:{set_code.lower()}',
                f'name:"{quoted_variant}" set.ptcgoCode:{set_code}',
                f'name:"{quoted_variant}"'
            ])

            for token_query in build_tokenized_queries(variant):
                queries.extend([
                    f'{token_query} set.id:{set_code.lower()}',
                    f'{token_query} set.ptcgoCode:{set_code}',
                    f'{token_query}'
                ])

        seen_queries = set()
        query_cache = {}

        def run_query(q):
            if q in query_cache:
                return query_cache[q]
            if q in seen_queries:
                return []
            seen_queries.add(q)
            try:
                results_q = Card.where(q=q, pageSize=CARD_QUERY_PAGE_SIZE)
            except:
                results_q = []
            query_cache[q] = results_q
            return results_q

        seen_ids = set()
        cards = []

        for q in queries:
            results_q = run_query(q)
            if not results_q:
                continue

            for c in results_q:
                if c.id not in seen_ids:
                    seen_ids.add(c.id)
                    cards.append(c)

            if any(
                str(c.number).upper() in possible_numbers and
                hasattr(c, "set") and
                c.set and
                (
                    c.set.ptcgoCode == set_code or
                    c.set.id.lower() == set_code.lower()
                )
                for c in cards
            ):
                break

        if ("unit energy" in norm(name) or "blend energy" in norm(name)) and not cards:
            try:
                base_name = "Unit Energy" if "unit energy" in norm(name) else "Blend Energy"
                loose = run_query(f'name:"{base_name}"')
                for c in loose:
                    if c.id not in seen_ids:
                        seen_ids.add(c.id)
                        cards.append(c)
            except:
                pass

        return (norm(name), number, set_code), cards

    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        futures = [ex.submit(fetch, item) for item in unique_items.values()]

        for f in as_completed(futures):
            key, cards = f.result()
            results[key] = cards

    return results

### Extract energy letters from card name for matching unit/blend energies (you can probably edit this if there are more weird card names I formot)
def extract_energy_letters(name):
    return sorted(re.findall(r"\{([A-Z])\}", name))

### Resolve the best matching card from the candidates (There is for sure a better way but this is good enough for now)
def resolve(cards, name, number, set_code):
    if not cards:
        return None

    target_name = norm(name)
    target_number = str(number).upper()

    best = None
    best_score = -999

    for c in cards:
        score = 0

        card_name = norm(c.name)
        card_number = str(c.number).upper()

        # exact name
        if card_name == target_name:
            score += 100

        # partial name
        elif target_name in card_name:
            score += 50

        # exact number
        if card_number == target_number:
            score += 100
        elif target_number and card_number.endswith(target_number):
            score += 50

        # set similarity
        if hasattr(c, "set") and c.set:
            sid = c.set.id.lower()

            if set_code.lower() in sid:
                score += 50

            if c.set.ptcgoCode:
                if c.set.ptcgoCode.upper() == set_code.upper():
                    score += 100

        # prefer cards with images
        if hasattr(c, "images"):
            score += 5

        if score > best_score:
            best_score = score
            best = c

    return best

### Build the list of image URLs based on the decklist
def build_image_list(deck_lines):
    unique, counts = build_unique(deck_lines)
    candidate_map = fetch_candidates(unique)

    images = []

    for (name, number, set_code), item in unique.items():
        cards = candidate_map.get((name, number, set_code), [])

        card = resolve(cards, item["name"], item["number"], item["set_code"])

        if not card:
            print(f"Missing: {item['name']}")
            continue

        url = card.images.large
        images.extend([url] * counts[(name, number, set_code)])

    return images

### Draw a grid for cutting guides
def draw_grid(c, x0, y0):
    c.setLineWidth(.5)
    c.setStrokeColor(colors.gray)
    c.setDash(1, 2)

    for i in range(1, COLS):
        x = x0 + i * CARD_W
        c.line(x, y0, x, y0 + ROWS * CARD_H)

    for j in range(1, ROWS):
        y = y0 + j * CARD_H
        c.line(x0, y, x0 + COLS * CARD_W, y)

    c.setDash()

### Generates a PDF with the card images laid out in a grid, ready for printing and cutting
def prefetch_images(image_urls, max_workers=12):
    unique_urls = list(dict.fromkeys(image_urls))
    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        futures = [ex.submit(get_image, url) for url in unique_urls]
        for f in as_completed(futures):
            try:
                f.result()
            except:
                pass


def create_pdf(image_urls, filename="proxies.pdf"):
    prefetch_images(image_urls)
    c = canvas.Canvas(
        filename,
        pagesize=(COLS * CARD_W, ROWS * CARD_H),
        pageCompression=0
        )
    x0, y0 = 0, 0
    for i, url in enumerate(image_urls):
        row = (i // COLS) % ROWS
        col = i % COLS
        if i % (COLS * ROWS) == 0 and i > 0:
            #draw_grid(c, x0, y0)
            c.showPage()
        img = get_image(url)

        x = col * CARD_W
        y = (ROWS - 1 - row) * CARD_H

        c.drawImage(
            ImageReader(img),
            x, y,
            width=CARD_W,
            height=CARD_H,
            preserveAspectRatio=True,
            mask='auto'
        )
        c.setFont("Helvetica", 3)
        c.setFillColor(colors.gray)
        c.drawCentredString(
            x + 3*CARD_W / 4,
            y + 1,
            "Unofficial proxy. For personal use only."
        )
    if GRID_BOOL:   
        draw_grid(c, x0, y0)
    print("Done.")
    print("Created {} proxy cards across {} pages.".format(len(image_urls), c.getPageNumber()))
    c.save()

if __name__ == "__main__":
    settings_resolved = False
    print("Make sure you have your API key set in a .env file as API_KEY. " \
    "Not required but speeds up API calls and reduces rate limiting.. Available for free at https://pokemontcg.io/.")
    while(settings_resolved != True):
        print("\nCURRENT SETTINGS:")
        print("Target Image DPI:", TARGET_DPI)
        print("Output File Path:", OUTPUT_FILE)
        print("Decklist File Path:", DECKLIST_FILE)
        print("Draw Cutting Grid:", GRID_BOOL)
        print("PRINT TWEAKS - Saturation: {}, Brightness: {}, Contrast: {}".format(SATURATION, BRIGHTNESS, CONTRAST))
        cont = input("\nWould you like to proceed with these settings? [Y/N] ") or "Y"
        if cont.upper() != "Y":
            TARGET_DPI = int(input("\nEnter target DPI for images (default: 600): ") or TARGET_DPI)
            TARGET_W = int(CARD_WIDTH_IN * TARGET_DPI)  
            TARGET_H = int(CARD_HEIGHT_IN * TARGET_DPI)  
            OUTPUT_FILE = input("Enter output PDF file name (default: AutoGeneratedProxies.pdf): ") or OUTPUT_FILE
            DECKLIST_FILE = input("Enter decklist file name (default: decklist.txt): ") or DECKLIST_FILE
            drawG = input("Draw cutting grid lines on PDF? (default: N): [Y/N] ") or "N"
            if drawG.upper() != "Y":
                GRID_BOOL = False
            else:
                GRID_BOOL = True
            SATURATION = float(input("Enter saturation level (default: 1.15): ") or SATURATION)
            BRIGHTNESS = float(input("Enter brightness level (default: 1.06): ") or BRIGHTNESS)
            CONTRAST = float(input("Enter contrast level (default: 1.08): ") or CONTRAST)
        else:
            settings_resolved = True

    print("\nReading decklist from file...", end=" ")
    with open(DECKLIST_FILE, "r", encoding="utf-8") as f:
        deck_lines = f.readlines()
    print("Done.")

    print("Gathering card data and images from decklist...", end=" ")
    images = build_image_list(deck_lines)
    print("Done.")
    print("\nFound {} total cards to proxy. ".format(len(images)))

    full_path = os.path.abspath(OUTPUT_FILE)
    try:
        print("\nCreating PDF...", end=" ")
        create_pdf(images, OUTPUT_FILE)
    except Exception as e:
        print("ERROR: Failed to create PDF.", e)
    print("PDF saved to:", full_path)
    if os.path.exists(full_path):
        try:
            print("Now opening PDF.")
            os.startfile(full_path)
        except Exception as e:
            print("ERROR: Failed to open PDF.", e)
    else:
        print("ERROR: file not found")
    input("\nPress Enter to exit.")