'''
ProxiesFromDeck.py
Kale Stahl
Last Updated: 5/7/2026
'''

import os
import re
import unicodedata
from concurrent.futures import ThreadPoolExecutor, as_completed
import requests
from io import BytesIO
from PIL import Image
from pokemontcgsdk import Card, RestClient
from reportlab.pdfgen import canvas
from reportlab.lib.units import mm
from reportlab.lib.utils import ImageReader
from reportlab.lib import colors

### Set your API key (get one for free at https://pokemontcg.io/)
from dotenv import load_dotenv
load_dotenv()
api_key = os.getenv("API_KEY")
RestClient.configure(api_key)

### Constants
CARD_W = 63.5 * mm
CARD_H = 88.5 * mm
COLS = 3
ROWS = 3
OUTPUT_FILE = "AutoGeneratedProxies.pdf"
DECKLIST_FILE = "decklist.txt"
GRID_BOOL = False  # Set to True to draw cutting grid lines on the PDF"

image_cache = {}

### This can be changed if you want better resolution.
TARGET_DPI = 600
CARD_WIDTH_IN = 63.5 / 25.4
CARD_HEIGHT_IN = 88.5 / 25.4

TARGET_W = int(CARD_WIDTH_IN * TARGET_DPI)  
TARGET_H = int(CARD_HEIGHT_IN * TARGET_DPI)  

### Get image from URL with caching and upscale to target print resolution
def get_image(url):
    if url not in image_cache:
        r = requests.get(url)
        img = Image.open(BytesIO(r.content)).convert("RGB")

        # Upscale to target print resolution
        img = img.resize((TARGET_W, TARGET_H), Image.LANCZOS)

        from PIL import ImageFilter
        img = img.resize((TARGET_W, TARGET_H), Image.LANCZOS)
        img = img.filter(ImageFilter.UnsharpMask(radius=0.5, percent=120, threshold=2))

        image_cache[url] = img

    return image_cache[url]

### Parse a line of the decklist - expects format like "4 Pikachu BWP 25"
def parse_line(line):
    match = re.match(r"(\d+)\s+(.+?)\s+([A-Z0-9\-]+)\s+(\d+)", line)
    if not match:
        return None
    return int(match.group(1)), match.group(2), match.group(3), match.group(4)

### Normalize card name for API queries - convert stars to symbols and energy letters to {L}, {W}, etc. to maximize chances of matching weird card names in the API
def normalize_name_for_api(name):
    name = re.sub(r"\bprism\s*star\b", "◇", name, flags=re.IGNORECASE)
    name = re.sub(r"\bstar\b", "★", name, flags=re.IGNORECASE)

    def replace_energy(match):
        letters = match.group(1)
        return " ".join(f"{{{c}}}" for c in letters)

    name = re.sub(r"\b([LWMFPDC]+)\b$", replace_energy, name)

    name = re.sub(r"\s+", " ", name).strip()
    return name

### Normalize text for matching - remove accents, lowercase, and normalize stars to maximize chances of matching weird card names in the API
def norm(text):
    text = text.lower()

    # Normalize star both ways for matching
    text = text.replace("★", "star")
    text = text.replace("◇", "prism star")

    # Normalize unicode accents but KEEP symbols
    text = unicodedata.normalize("NFKD", text)
    text = "".join(c for c in text if not unicodedata.combining(c))

    return text

### Build a unique set of cards from the decklist, keyed by normalized name + number + set code to minimize API calls
def build_unique(deck_lines):
    unique = {}

    for line in deck_lines:
        parsed = parse_line(line)
        if not parsed:
            continue

        count, name, set_code, number = parsed
        key = (norm(name), number, set_code.upper())

        if key not in unique:
            unique[key] = {
                "name": name,
                "number": number,
                "set_code": set_code.upper()
            }

    return unique

### Build possible number variants based on set code and original number, to maximize chances of matching weird promo numbering schemes
### (Limitless/TGCLive uses different numbering sometimes so this hopefully catches those)
def build_possible_numbers(number, set_code):
    number = str(number).upper().strip()
    nums = {number}

    try:
        n_int = int(number)
    except:
        n_int = None

    if set_code == "BWP":
        if n_int is not None:
            nums.update({
                f"BW{n_int}",
                f"BW{n_int:02d}",
                str(n_int)
            })

    elif set_code == "XYP":
        if n_int is not None:
            nums.update({
                f"XY{n_int}",
                f"XY{n_int:02d}",
                str(n_int)
            })

    elif set_code == "SMP":
        if n_int is not None:
            nums.update({
                f"SM{n_int}",
                f"SM{n_int:02d}",
                str(n_int)
            })
    elif set_code == "WP":
        if n_int is not None:
            nums.update({
                f"WP{n_int}",
                f"WP{n_int:02d}",
                str(n_int)
            })

    # General fallback for weird promos
    if n_int is not None:
        nums.add(str(n_int))

    return nums

### Fetch candidate cards from API for each unique item in the decklist, using multiple query strategies to maximize chances
### of finding a match. There is 10000% a better way to do this, but this is what I first came up with and it seems to not break always.
def fetch_candidates(unique_items, max_workers=12):
    results = {}

    def fetch(item):
        name = item["name"]
        number = item["number"]
        set_code = item["set_code"]

        api_name = normalize_name_for_api(name)
        possible_numbers = build_possible_numbers(number, set_code)

        queries = []

        # Try all number variants
        for num in possible_numbers:
            queries.extend([
                f'name:"{api_name}" number:{num} set.ptcgoCode:{set_code}',
                f'name:"{api_name}" number:{num} set.id:{set_code.lower()}',
                f'name:"{api_name}" number:{num}'
            ])

        # Fallbacks without number
        queries.extend([
            f'name:"{api_name}" set.id:{set_code.lower()}',
            f'name:"{api_name}" set.ptcgoCode:{set_code}',
            f'name:"{api_name}"'
        ])

        seen_ids = set()
        cards = []

        for q in queries:
            try:
                results_q = Card.where(q=q)
            except:
                continue

            for c in results_q:
                if c.id not in seen_ids:
                    seen_ids.add(c.id)
                    cards.append(c)

            if any(str(c.number).upper() in possible_numbers for c in cards):
                break
            if "unit energy" in norm(name) or "blend energy" in norm(name):
                try:
                    base_name = "Unit Energy" if "unit energy" in norm(name) else "Blend Energy"
                    loose = Card.where(q=f'name:"{base_name}"')

                    for c in loose:
                        if c.id not in seen_ids:
                            seen_ids.add(c.id)
                            cards.append(c)
                except:
                    pass

        return (norm(name), number, set_code), cards

    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        futures = [ex.submit(fetch, item) for item in unique_items.values()]

        for f in as_completed(futures):
            key, cards = f.result()
            results[key] = cards

    return results

### Extract energy letters from card name for matching unit/blend energies (you can probably edit this if there are more weird card names I formot)
def extract_energy_letters(name):
    return sorted(re.findall(r"\{([A-Z])\}", name))

### Resolve the best matching card from the candidates (There is for sure a better way but this is good enough for now)
def resolve(cards, name, number, set_code):
    if not cards:
        return None
    
    target_letters = sorted(list(number)) if "energy" in norm(name) else None

    for c in cards:
        if "energy" in norm(name):
            card_letters = extract_energy_letters(c.name)
            if card_letters == target_letters:
                return c

    possible_numbers = build_possible_numbers(number, set_code)

    for c in cards:
        if hasattr(c, "set") and c.set:
            if (
                str(c.number).upper() in possible_numbers and
                (c.set.id.lower() == set_code.lower() or
                 (set_code == "WP" and c.set.id.lower() == "basep"))
            ):
                return c

    for c in cards:
        if str(c.number).upper() in possible_numbers:
            return c

    for c in cards:
        if norm(name) in norm(c.name):
            if str(c.number).upper() in possible_numbers:
                return c

    return None

### Build the list of image URLs based on the decklist
def build_image_list(deck_lines):
    unique = build_unique(deck_lines)
    candidate_map = fetch_candidates(unique)

    images = []

    for (name, number, set_code), item in unique.items():
        cards = candidate_map.get((name, number, set_code), [])

        card = resolve(cards, item["name"], item["number"], item["set_code"])

        if not card:
            print(f"Missing: {item['name']}")
            continue

        url = card.images.large

        for line in deck_lines:
            parsed = parse_line(line)
            if not parsed:
                continue

            c, n, s, num = parsed
            if norm(n) == name and num == number and s.upper() == set_code:
                images.extend([url] * c)

    return images

### Draw a grid for cutting guides
def draw_grid(c, x0, y0):
    c.setLineWidth(.5)
    c.setStrokeColor(colors.gray)
    c.setDash(1, 2)

    for i in range(1, COLS):
        x = x0 + i * CARD_W
        c.line(x, y0, x, y0 + ROWS * CARD_H)

    for j in range(1, ROWS):
        y = y0 + j * CARD_H
        c.line(x0, y, x0 + COLS * CARD_W, y)

    c.setDash()

### Generates a PDF with the card images laid out in a grid, ready for printing and cutting
def create_pdf(image_urls, filename="proxies.pdf"):
    c = canvas.Canvas(
        filename,
        pagesize=(COLS * CARD_W, ROWS * CARD_H),
        pageCompression=0
        )
    x0, y0 = 0, 0
    for i, url in enumerate(image_urls):
        row = (i // COLS) % ROWS
        col = i % COLS
        if i % (COLS * ROWS) == 0 and i > 0:
            #draw_grid(c, x0, y0)
            c.showPage()
        img = get_image(url)

        x = col * CARD_W
        y = (ROWS - 1 - row) * CARD_H

        c.drawImage(
            ImageReader(img),
            x, y,
            width=CARD_W,
            height=CARD_H,
            preserveAspectRatio=True,
            mask='auto'
        )
        c.setFont("Helvetica", 3)
        c.setFillColor(colors.gray)
        c.drawCentredString(
            x + 3*CARD_W / 4,
            y + 1,
            "Unofficial proxy. For personal use only."
        )
    if GRID_BOOL:   
        draw_grid(c, x0, y0)
    print("Done.")
    print("Created {} proxy cards across {} pages.".format(len(image_urls), c.getPageNumber()))
    c.save()

if __name__ == "__main__":
    settings_resolved = False
    print("Make sure you have your API key set in a .env file as API_KEY. " \
    "Not required but speeds up API calls and reduces rate limiting.. Available for free at https://pokemontcg.io/.")
    while(settings_resolved != True):
        print("\nCURRENT SETTINGS:")
        print("Target Image DPI:", TARGET_DPI)
        print("Output File Path:", OUTPUT_FILE)
        print("Decklist File Path:", DECKLIST_FILE)
        print("Draw Cutting Grid:", GRID_BOOL)
        cont = input("\nWould you like to proceed with these settings? [Y/N] ") or "Y"
        if cont.upper() != "Y":
            TARGET_DPI = int(input("\nEnter target DPI for images (default: 600): ") or TARGET_DPI)
            TARGET_W = int(CARD_WIDTH_IN * TARGET_DPI)  
            TARGET_H = int(CARD_HEIGHT_IN * TARGET_DPI)  
            OUTPUT_FILE = input("Enter output PDF file name (default: AutoGeneratedProxies.pdf): ") or OUTPUT_FILE
            DECKLIST_FILE = input("Enter decklist file name (default: decklist.txt): ") or DECKLIST_FILE
            drawG = input("Draw cutting grid lines on PDF? (default: N): [Y/N] ") or "N"
            if drawG.upper() != "Y":
                GRID_BOOL = False
            else:
                GRID_BOOL = True
        else:
            settings_resolved = True

    print("\nReading decklist from file...", end=" ")
    with open(DECKLIST_FILE, "r", encoding="utf-8") as f:
        deck_lines = f.readlines()
    print("Done.")

    print("Gathering card data and images from decklist...", end=" ")
    images = build_image_list(deck_lines)
    print("Done.")
    genpdf = input("\nFound {} total cards to proxy. Proceed to generating PDF? [Y/N] ".format(len(images))) or "Y"
    if genpdf.upper() != "Y":
        print("Quitting without generating PDF. Check your settings and decklist and try again.")

    full_path = os.path.abspath(OUTPUT_FILE)
    try:
        print("\nCreating PDF...", end=" ")
        create_pdf(images, OUTPUT_FILE)
    except Exception as e:
        print("ERROR: Failed to create PDF.", e)
    print("PDF saved to:", full_path)
    if os.path.exists(full_path):
        try:
            print("Now opening PDF.")
            os.startfile(full_path)
        except Exception as e:
            print("ERROR: Failed to open PDF.", e)
    else:
        print("ERROR: file not found")
    input("\nPress Enter to exit.")